//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/MapControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MapControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MapControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MapControl"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""115dc110-95c4-416a-a8c4-6c163f599aa6"",
            ""actions"": [
                {
                    ""name"": ""PrimaryC"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dd656648-f786-49d1-b96e-36b2bcb87660"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPos"",
                    ""type"": ""PassThrough"",
                    ""id"": ""725c6059-9b78-4b79-90c7-2139843228d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6c031fc8-bc93-4bfd-89b7-66706d56767c"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abbd0638-f2da-4fbe-aecc-779a81823f65"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_PrimaryC = m_Touch.FindAction("PrimaryC", throwIfNotFound: true);
        m_Touch_PrimaryPos = m_Touch.FindAction("PrimaryPos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
    private readonly InputAction m_Touch_PrimaryC;
    private readonly InputAction m_Touch_PrimaryPos;
    public struct TouchActions
    {
        private @MapControl m_Wrapper;
        public TouchActions(@MapControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryC => m_Wrapper.m_Touch_PrimaryC;
        public InputAction @PrimaryPos => m_Wrapper.m_Touch_PrimaryPos;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void AddCallbacks(ITouchActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
            @PrimaryC.started += instance.OnPrimaryC;
            @PrimaryC.performed += instance.OnPrimaryC;
            @PrimaryC.canceled += instance.OnPrimaryC;
            @PrimaryPos.started += instance.OnPrimaryPos;
            @PrimaryPos.performed += instance.OnPrimaryPos;
            @PrimaryPos.canceled += instance.OnPrimaryPos;
        }

        private void UnregisterCallbacks(ITouchActions instance)
        {
            @PrimaryC.started -= instance.OnPrimaryC;
            @PrimaryC.performed -= instance.OnPrimaryC;
            @PrimaryC.canceled -= instance.OnPrimaryC;
            @PrimaryPos.started -= instance.OnPrimaryPos;
            @PrimaryPos.performed -= instance.OnPrimaryPos;
            @PrimaryPos.canceled -= instance.OnPrimaryPos;
        }

        public void RemoveCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnPrimaryC(InputAction.CallbackContext context);
        void OnPrimaryPos(InputAction.CallbackContext context);
    }
}
